### PR TITLE
Adding a Windowbuilder Basic UI Preference

### PR DESCRIPTION
**Pull request by MarcelS4**
This preference will be used to hide multiple UI elements under a single
flag instead of setting multiple flags for each element

### CODE REVIEW

**Comment by vogella** [comment]
Looks good. Thanks @MarcelS4

**Comment by wimjongman** [comment]
This workflow of creating new pull requests for every change review is very confusing. I don't know why you insist on creating a new squashed PR for every review? Maybe we can discuss this in a meeting?

**Comment by lcaron** [comment]
Very good idea ! When are you available for a chat ?

**Comment by wimjongman** [comment]
All-day next Monday, Thursday, and Friday.

**Comment by MarcelS4** [comment]
I'm available on Thursday 07:00 - 16:00 CAT and 07:00 - 13:00 CAT on Friday

**Comment by lcaron** [comment]
I'm available Friday

**Comment by MarcelS4** [comment]
What time will we meet on Friday? @wimjongman  does that suit you?

**Comment by wimjongman** [comment]
Microsoft Teams meeting 
Join on your computer or mobile app 
[Click here to join the meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDIxYWU2M2YtMmZhZi00ZGEzLWFiNjctOWVhOGMxZjIwMjRl%40thread.v2/0?context=%7b%22Tid%22%3a%22b0e58deb-57b7-4d39-8efc-562c88e8939b%22%2c%22Oid%22%3a%226013ebcb-abd8-40f8-8436-cdfecbe07e02%22%7d) 
 
[Learn More](https://aka.ms/JoinTeamsMeeting) | [Meeting options](https://teams.microsoft.com/meetingOptions/?organizerId=6013ebcb-abd8-40f8-8436-cdfecbe07e02&tenantId=b0e58deb-57b7-4d39-8efc-562c88e8939b&threadId=19_meeting_MDIxYWU2M2YtMmZhZi00ZGEzLWFiNjctOWVhOGMxZjIwMjRl@thread.v2&messageId=0&language=en-US)

**Comment by wimjongman** [comment]
Friday March 24: 14:00-15:00 CET

Microsoft Teams meeting 
Join on your computer or mobile app 
[Click here to join the meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDIxYWU2M2YtMmZhZi00ZGEzLWFiNjctOWVhOGMxZjIwMjRl%40thread.v2/0?context=%7b%22Tid%22%3a%22b0e58deb-57b7-4d39-8efc-562c88e8939b%22%2c%22Oid%22%3a%226013ebcb-abd8-40f8-8436-cdfecbe07e02%22%7d) 
 
[Learn More](https://aka.ms/JoinTeamsMeeting) | [Meeting options](https://teams.microsoft.com/meetingOptions/?organizerId=6013ebcb-abd8-40f8-8436-cdfecbe07e02&tenantId=b0e58deb-57b7-4d39-8efc-562c88e8939b&threadId=19_meeting_MDIxYWU2M2YtMmZhZi00ZGEzLWFiNjctOWVhOGMxZjIwMjRl@thread.v2&messageId=0&language=en-US)

**Comment by MarcelS4** [comment]
@wimjongman do you mean Thursday March 24? or Friday March 25?

**Pull request merged**
