### PR TITLE
Update maven.yaml

### PR DESCRIPTION
**Pull request by laeubi**
Use batch compile and print version info of maven.

### CODE REVIEW

**Comment by vogella** [comment]
Thanks, looks like you use the wrong credentions? Anonymous (mail@****.de)

**Comment by laeubi** [comment]
@vogella yes GH messed this up but you might simply want to apply this directly to the master branch as this is not really "code", or merge this as this is not really IP relevant :-)

**Comment by vogella** [comment]
If possible please just force-push an updated commit, I assume that is easy on your side. Never mess with lawyers.

**Comment by laeubi** [comment]
I did this directly from the GH UI... so no local copy of that where I could adjust/force push anything :-\

**Pull request closed without merging**
