### PR TITLE
Updated Guava lib

### PR DESCRIPTION
**Pull request by MarcelS4**
Guava library removed from lib project and added to Target Platform. The
libarary has also been updated to the latest version to avoid security
risks

### CODE REVIEW

**Review by wimjongman — APPROVED** [review]
Thanks, Marcel!

**Comment by wimjongman** [comment]
You can squash and merge.

**Comment by MarcelS4** [comment]
@wimjongman thank you. I however have no merge options available to me

**Comment by MarcelS4** [comment]
@wimjongman both my git account and eclipse account use the same email address. I have signed the Eclipse Contributor Agreement, but that was the only agreement I received?

**Comment by MarcelS4** [comment]
@jonahgraham Thanks for the info, I have checked and my GitHub username is linked to my account

**Comment by MarcelS4** [comment]
@wimjongman I have sent the request now to join the wb-dev mailing list

**Review by vogella — COMMENTED** [review]
With this change I get java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableMap
	at org.eclipse.wb.tests.designer.core.model.description.DescriptionVersionsProvidersTest$DescriptionVersionsProviderFactory_2.getVersions(DescriptionVersionsProvidersTest.java:321)

Can you rebase onto master and run our test suite and verify that you see the same error?

**Comment by vogella** [comment]
@MarcelS4 please rebase onto master and run the tests again. After https://github.com/eclipse/windowbuilder/commit/f30b28fee626dc09dd1247fd0798ed59d64e433d they run fine for me before and after your change. Please remember to reload your target platform if you switch commits.

If tests are also green for you, we can merge.

**Comment by vogella** [comment]
Did you test this @MarcelS4 ?

**Comment by MarcelS4** [comment]
@vogella not yet. Currently testing the Beanutils PR then will test this one

**Comment by MarcelS4** [comment]
@vogella Rebased and tested. No errors or failures in the WindowbuilderTests test suite

**Comment by vogella** [comment]
Thanks @MarcelS4 Merged

**Pull request merged**
