### PR TITLE
Hididng context menu options

### PR DESCRIPTION
**Pull request by MarcelS4**
Closes issue #120

### CODE REVIEW

**Comment by vogella** [comment]
@MarcelS4 please sqasch all commits into one commit and force push to your branch to update this pull request. I know @wimjongman asked you not to do this but as we is currently not reviewing WB pull lets do it me preferred way :-0

**Comment by MarcelS4** [comment]
Updated to use the Windowbuilder Basic Preference

**Comment by vogella** [comment]
Please merge commits and use new constant which you will introduce in the new PR.

**Comment by vogella** [comment]
You can rebase  this change on the new commit.

**Comment by MarcelS4** [comment]
Please see PR #158

**Pull request closed without merging**
