### PR TITLE
[GEF] Replace the Dimension class with its latest GEF counterpart

### PR DESCRIPTION
**Pull request by ptziegler**
The original class has been extended by the union() method, accepting the width and height as raw ints. The remaining methods are already compatible with our class, meaning we can simply remove the old class and only have to adapt the package.

### CODE REVIEW

**Comment by vogella** [comment]
I would hold this one until we have a "clean" build, i.e. no unit test failures.

**Comment by ptziegler** [comment]
I agree. That's why it's still a draft :)

**Comment by ptziegler** [comment]
The test error seems to be unrelated to the changes but rather due to Windows' wonky file system. I have a few ideas how those can be stabilized, but that'd be a separate PR.

**Comment by ptziegler** [comment]
I think the only thing holding us back right now are the sporadic test failures. With all of our changes to the Draw2D geometry classes and the Java 17, we can finally start with the GEF-classic migration.

**Pull request merged**
