### PR TITLE
Windowbuilder Basic UI Preference Constant

### PR DESCRIPTION
**Pull request by MarcelS4**
This pull request adds a preference to WB called WB_BASIC_UI. 

This preference will be used to hide multiple UI elements from the Windowbuilder UI to simplify the UI without having to set multiple flags.

### CODE REVIEW

**Comment by vogella** [comment]
Why is this closed? You can force push to a branch to update a PR. Please squash your commits and updarte this pull request.

**Comment by MarcelS4** [comment]
@vogella I closed it because wasnt supposed to contain those commits. I tried creating a new branch form my origin/master branch and it contained those commits. When selecting those commits I do not have the option to squash them. So I closed it, to try and create a new branch

**Comment by vogella** [comment]
What is the new PR?

On Fri, Jan 21, 2022 at 10:04 AM MarcelS4 ***@***.***> wrote:
>
> @vogella I closed it because wasnt supposed to contain those commits. I tried creating a new branch form my origin/master branch and it contained those commits. When selecting those commits I do not have the option to squash them. So I closed it, to try and create a new branch
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
Eclipse Platform project co-lead
CEO vogella GmbH

Haindaalwisch 17a, 22395 Hamburg
Amtsgericht Hamburg: HRB 127058
Geschäftsführer: Lars Vogel, Jennifer Nerlich de Vogel
USt-IdNr.: DE284122352
Fax (040) 5247 6322, Email: ***@***.***, Web: http://www.vogella.com

**Comment by MarcelS4** [comment]
@vogella Hi Lars, the new PR is #155

**Comment by vogella** [comment]
Thanks @MarcelS4

**Pull request closed without merging**
