### PR TITLE
Fix WindowBuilder 1.9.8 fails to run with IBM Semeru Java 17

### PR DESCRIPTION
**Pull request by howlger**
Running WindowBuilder 1.9.8 with the [_IBM Semeru Runtime Open Edition 17.0.3.0 (build 17.0.3+7)_](https://developer.ibm.com/semeru-runtime-downloads/) Java 17 VM on Windows 10 causes a NPE, when e.g. invoking _File > New > Other...: WindowBuilder > Swing Designer > Application Window_:
```
org.osgi.framework.BundleException: Error starting module.
osgi.identity; osgi.identity="org.eclipse.wb.core.java";
type="osgi.bundle"; version:Version="1.9.2.202203170939";
singleton:="true" [id=465]
    ...
Caused by: java.lang.NullPointerException
	at java.base/java.lang.Class.getModule(Class.java)
	at java.base/sun.invoke.util.VerifyAccess.isClassAccessible(VerifyAccess.java:227)
	at java.base/java.lang.invoke.MethodHandles$Lookup.isClassAccessible(MethodHandles.java:3703)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkSymbolicClass(MethodHandles.java:3691)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3652)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2594)
	at io.github.toolfactory.jvm.function.catalog.PrivateLookupInMethodHandleSupplier$ForJava9.<init>(PrivateLookupInMethodHandleSupplier.java:69)
	... 184 more
```
Updating the following dependencies to their latest versions from Maven
Central fixes the issue:
- org.burningwave:core - from 12.4.0 to [12.53.0](https://mvnrepository.com/artifact/org.burningwave/core/12.53.0)
- org.burningwave:jvm-driver - from 6.0.0 to [8.6.0](https://mvnrepository.com/artifact/org.burningwave/jvm-driver/8.6.0)
- io.github.toolfactory:jvm-driver - from 8.0.0 to [9.1.1](https://mvnrepository.com/artifact/io.github.toolfactory/jvm-driver/9.1.1)

### CODE REVIEW

**Comment by wimjongman** [comment]
Thanks!!

**Comment by vogella** [comment]
@howlger I get tons of compile errors now if my windowsbuilder workspace. Do you see the same? If you run the WindowBuilderTests test suite, are all tests green for you?

**Comment by howlger** [comment]
> @howlger I get tons of compile errors now if my windowsbuilder workspace. Do you see the same? If you run the WindowBuilderTests test suite, are all tests green for you?

I ran a full build that also included UI tests and that succeeded, and tested the outcome of that before I did the pull request.

Could you please track down it a bit more? I don't see anything that could cause problems here.

**Comment by vogella** [comment]
Unfortunately most of the WB tests are not yet ready for Tycho. Please open WindowBuilderTests and run it from your IDE to check if this change is really OK, this will run ~6000 tests compared to the ~100 tests I added to Tycho.

**Comment by wimjongman** [comment]
I'm sorry for the early release. I did not realize the tests did not run in Tycho.

**Comment by howlger** [comment]
@vogella Sorry, I was not aware of `WindowBuilderTests`.

I tried to set up everything from scratch according to [`CONTRIBUTING.md`](https://github.com/eclipse/windowbuilder/blob/master/CONTRIBUTING.md). Unfortunately, this did not completely succeed and I had to do some manual steps and adjustments to get the code and for it to compile so that I'm now able to run `WindowBuilderTests`.

I see 6818 `WindowBuilderTests` tests: after running 6029 tests (from which 31 failed) it got stuck in `org.eclipse.wb.tests.designer.rcp.model.widgets.ViewFormGefTest.test_canvas_MOVE`. After I commented out this test, there were 5 errors and 40 failures. Did all 6818 tests work before this change?

Is the problem that some functions no longer work, or that it causes false positive tests? In the first case, I would recommend to revert the change, since I don't know how WindowBuilder can be fixed in a way other than updating the libraries to make it work with an OpenJ9 Java 17 VM, and since the HotSpot VM has a larger market share.

**Comment by vogella** [comment]
@howlger thanks for helping here.

Could you send a PR for the additional steps of setup?

The tests used to work, we sometimes had some issues with the model tests and if one or multiple tests fails, you end up with such more as the cleanup of the test seems to break if some of them are failing. Can you upload a screenshot of your failing tests?

**Comment by howlger** [comment]
When I press _Perform Setup Tasks..._, setting the target platform fails, probably for the [dependencies from Maven Central](https://github.com/eclipse/windowbuilder/blob/423160263a3b1ba75773282ed8da6859375e6843/target-platform/wb.target#L12-L61) (maybe @merks can tell if this already supported or the [Oomph setup](https://github.com/eclipse/windowbuilder/blob/master/setups) has to be adapted):

```
ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:151)
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:905)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
    ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1655737284074
    ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: WindowBuilder Core 1.10.1.202203170939 (org.eclipse.wb.core 1.10.1.202203170939) requires 'osgi.bundle; com.google.guava 31.1.0' but it could not be found
    ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
      ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1655737284074
      ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.wb.core 0.0.0
```
As a workaround, I manually opened `/target-platform/wb.target` and clicked the _Set as Active Target Platform_ link the upper right corner of the editor.

Then some projects could not be built because other depending projects could not be built either. After some manual changes of the Java version on some projects, it compiled. But after I reverted the changes, a cleaning all projects did not cause any problem. Maybe it is related to cyclic dependencies and the maximum iterations settings in the preferences _General > Workspace > Build_.

**Comment by merks** [comment]
That version is in the release train so it should be resolved:

https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/releases/2022-06/202206151000/index/com.google.guava_30.1.0.v20210127-2300.html

**Comment by merks** [comment]
Oh, you want version 31.  Is there some compelling reason for this?  The train already has multiple version of this, and we really **do not**  need more of them.

**Comment by howlger** [comment]
@merks Thanks for the insights.

@vogella I have reverted locally my two commits and the tests still fail. I don't know by what it is caused, but this change doesn't cause compile errors nor failing tests.

**Comment by vogella** [comment]
@howlger after 3x cleaning the projects and reloading the target platform, the project finally compiled again. Test are running fine at the moment, I see a few test failing on Windows 11 but this is unrelated to your change. Thanks. Good you provide another PR for moving the library to the maven target from @merks? The copied JAR files are really a legacy and it would be nice if we use every opportunity to reduce their usage. 

Follow-up issues (not related to this change but triggered by it, as I tried to verify WB after this change):

https://github.com/eclipse/windowbuilder/issues/284
https://github.com/eclipse/windowbuilder/issues/285
https://github.com/eclipse/windowbuilder/issues/286

**Pull request merged**
