### PR TITLE
Hiding wb toolbar

### PR DESCRIPTION
**Pull request by MarcelS4**
We needed the capability to hide the Windowbuilder toolbar as our application has its own toolbar that have similar functionality but not the same. Therefore to have both toolbars visible would cause confusion and interference. 

The problem was that there was no way to hide this toolbar from our application without altering the Windowbuilder itself. 

To solve this issue I have added a class called DesignCompositeManager that is used within Windowbuilder to determine whether to hide or show the WB toolbar. 

This is done by creating the DesignCompositeManager object and passing it into the constructor of the DesignerEditor in our application.

### CODE REVIEW

**Comment by MarcelS4** [comment]
Closes issue #110

**Comment by wimjongman** [comment]
Marcel, I find this a bit overkill for such a simple requirement. Can't you use an extra style bit to control the visibility of the toolbar?

**Comment by vogella** [comment]
Or a simple preference which can control this visibility? 

@wimjongman I'm not sure how the style bit suggestion should work, as the code is still internal to WB for the user. Can you clarify?

**Comment by wimjongman** [comment]
Lars, I think the same way Marcel intends to pass the new class around. All changed classes are internal. I think that your suggestion is even easier. If this is a corner use case, even a -Dorg.eclipse.wb.hidetoolbar=true property would be fine to me.

**Comment by MarcelS4** [comment]
I have removed the overkill implementation and used Lars suggestion of making use of preferences. Much simpler. Thank you

**Comment by vogella** [comment]
Created a cleanup version of this request in https://github.com/eclipse/windowbuilder/pull/143

**Comment by vogella** [comment]
.

**Pull request closed without merging**
