### PR TITLE
Fix calculation of shell insets in CoordinateUtilsTest

### PR DESCRIPTION
**Pull request by ptziegler**
While the shell is invisible, its coordinates are not properly updated. When attempting to calculate the shell location and client area insets, GTK returns junk coordinates to the WB. Which then results in nonsensical insets and bounds.

### CODE REVIEW

**Comment by ptziegler** [comment]
GTK is fun...

**Comment by ptziegler** [comment]
Great, it got stuck :(

See #400

**Comment by ptziegler** [comment]
And another one that works locally but fails on the build nodes :(

**Comment by ptziegler** [comment]
This seems to be the same issue as #389. The title bar doesn't have a height, hence why the client area starts at (0, 0). Which means I think it's for the best to disable that one for the time being, as well.

**Comment by vogella** [comment]
Fine to disable for me.

**Pull request merged**
