### PR TITLE
Simpliefied exception and warning composite

### PR DESCRIPTION
**Pull request by MarcelS4**
Closes issue #147 

Buttons on WarningComposite and ExceptionComposite can be hidden by setting the Windowbuilder Basic preference to 'true'

### CODE REVIEW

**Comment by vogella** [comment]
Please remove the merge commit. I typically recommend to use rebase strategy during pull. https://www.vogella.com/tutorials/Git/article.html#pullrebase Can also be set via Eclipse preferences in the Git section

**Comment by vogella** [comment]
Is this one still relevant? Or was it handled via https://github.com/eclipse/windowbuilder/pull/156?

**Comment by MarcelS4** [comment]
Apologies for not closing this, you are correct Lars. This one can be closed in favour of #156 and #158

**Comment by vogella** [comment]
No worries, please check the rest of the PR if they are still relevant.

**Pull request closed without merging**
