### PR TITLE
Bug 567207 - [Releng] Include Windowbuilder 1.9.5 in 4.18 Release Train - Various cleanups

### PR DESCRIPTION
**Pull request by akurtakov**
Trying to get a hold of codebase status before considering it for additiong to Java EPP

### CODE REVIEW

**Comment by akurtakov** [comment]
@wimjongman Something for you?

**Comment by wimjongman** [comment]
Jenkins ok to test

**Comment by wimjongman** [comment]
> 
> 
> @wimjongman Something for you?

Yes! Thank you for helping. 

For some reason, the CI is not yet integrated with GitHub. I filed [bug 568191](https://bugs.eclipse.org/bugs/show_bug.cgi?id=568191) for that.

We track these efforts in [bug 567207](https://bugs.eclipse.org/bugs/show_bug.cgi?id=567207)

**Review by wimjongman — APPROVED** [review]

**Comment by vogella** [comment]
We could use Github actions to check PR. I create a new PR for this.

**Comment by vogella** [comment]
@wimjongman you approved this change but did not merge it. Was that intentional?

**Comment by vogella** [comment]
Hm, I seem to have forgotten which command we run for the build "mvn clean verify" fails with the following error message for me:

[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.wb.releng.updatesite raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT
[ERROR]   Missing requirement: org.eclipse.wb.releng.updatesite raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT requires 'org.eclipse.wb.core.feature.feature.group [1.9.4,1.9.5)' but it could not be found
[ERROR]

**Comment by wimjongman** [comment]
> 
> 
> @wimjongman you approved this change but did not merge it. Was that intentional?

Yes, I want to build it first. Frederic fixed the build for us.  See bug 568191 for that.

**Comment by wimjongman** [comment]
Jenkins ok to test

**Comment by wimjongman** [comment]
Jenkins, retest this please

**Comment by wimjongman** [comment]
> 
> 
> Hm, I seem to have forgotten which command we run for the build "mvn clean verify" fails with the following error message for me:
> 
> [ERROR] Cannot resolve project dependencies:
> [ERROR] Software being installed: org.eclipse.wb.releng.updatesite raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT
> [ERROR] Missing requirement: org.eclipse.wb.releng.updatesite raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT requires 'org.eclipse.wb.core.feature.feature.group [1.9.4,1.9.5)' but it could not be found
> [ERROR]

@vogella that looks like an issue in the update site. See it in the build too. Features have been moved to 1.9.5. i guess 1.9.4 is still referenced somewhere?

**Comment by wimjongman** [comment]
Thanks, Alexander. This also fixed the build that I left hanging after the last emergency release.

**Pull request merged**
