### PR TITLE
WB tests fails with references to 32 bit and unsupported platforms

### PR DESCRIPTION
**Pull request by vogella**
WB still contains multiple references to 32 bit platform which have been
removed a longer time ago. With this change these references are
removed, which will allow to activate the SWT JUnit tests again.

### CODE REVIEW

**Comment by opcoach** [comment]
Hi Lars, 
I will check it on Mac

**Comment by vogella** [comment]
Thanks, @opcoach

**Comment by vogella** [comment]
I assume you are waiting with your test until the merge. Please test with Mac after the merge.

**Comment by opcoach** [comment]
Hi lars,

I focused on the other bug about cobtext spy and up to friday i am busy with a git traiking but it is in my priority list to test window builder on mac :)

**Comment by opcoach** [comment]
Hi Lars, 

I am ‘mavening’ window builder and will try it this afternoon :) 




  <http://www.opcoach.com/>
Olivier Prouvost

Formation et Expertise Eclipse

 	
 ***@***.***
 http://www.opcoach.com <http://www.opcoach.com/>
 +33(0)6 28 07 65 64
 OPCoach_Eclipse <https://twitter.com/OPCoach_Eclipse>
 Profil linkedin
 <https://fr.linkedin.com/in/olivierprouvost>	 	  <https://eclipse.org/membership/showMember.php?member_id=987>

**Comment by vogella** [comment]
Thanks @opcoach

**Comment by lcaron** [comment]
Happy to see @opcoach joining the WB Team ;)

**Comment by opcoach** [comment]
Hi Laurent ! @lcaron 

 It's fun to meet you again here, 5 or 6 years after your Eclipse training in Lyon ! :)

**Pull request merged**
