### PR TITLE
Ensure that the direct-from-maven dependences are PGP signed

### PR DESCRIPTION
**Pull request by merks**
The tycho-gpg-plugin is used for that purpose.

https://github.com/eclipse/windowbuilder/issues/302

### CODE REVIEW

**Comment by merks** [comment]
I see the platform does it like this in their pipeline:
```
		stage('initialize PGP') {
			steps {
				withCredentials([file(credentialsId: 'secret-subkeys.asc', variable: 'KEYRING')]) {
					sh 'gpg --batch --import "${KEYRING}"'
					sh 'for fpr in $(gpg --list-keys --with-colons  | awk -F: \'/fpr:/ {print $10}\' | sort -u); do echo -e "5\ny\n" |  gpg --batch --command-fd 0 --expert --edit-key ${fpr} trust; done'
				}
			}
		}
```

My EMF publish-to-maven job has this:

image

But that choice isn't there for the windowbuilder job:

image

@fredg02 Do we have to ask for something to be configured on the WindowBuilder ci instance?

**Comment by merks** [comment]
@mbarbero Do we have to ask for something to be configured on the WindowBuilder ci instance to support PGP signing?

@vogella Shall I merge this to see if it "just works"?

**Comment by mickaelistria** [comment]
> Do you know what, if anything, we need to do to ensure that the above job can do PGP signing?

Sorry, I only noticed the question. It seems like you found some answers already, but to confirm, yes, you need webmasters to install the project PGP key on the CI server as a credential/secret first. Then, you can configure the job as described in https://wiki.eclipse.org/Jenkins#How_can_artifacts_be_deployed_to_OSSRH_.2F_Maven_Central.3F
HTH

**Comment by merks** [comment]
@mickaelistria Thanks!! We all get so much mail since the github migration it's easy to overlook something...

I've opened this request:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1474

**Comment by merks** [comment]
Thanks!  😄  I'll test later today...

**Pull request merged**
