### PR TITLE
Retire discovery plug ins

### PR DESCRIPTION
**Pull request by vogella**

### CODE REVIEW

**Comment by vogella** [comment]
@MarcelS4 are you using these plug-ins?

**Comment by MarcelS4** [comment]
Not to my knowledge.

**Comment by vogella** [comment]
@wimjongman @lcaron any concerns? We anyhow do not include these in our delivery since years AFAICS.

**Comment by wimjongman** [comment]
Isn't that the mechanism to extend WB with for instance Nebula?

**Comment by vogella** [comment]
> Isn't that the mechanism to extend WB with for instance Nebula?

Not that I know of. @lcaron can you answer this?

**Comment by lcaron** [comment]
Hi

Sorry for my late answer, I'll check it today and get back to you

**Comment by lcaron** [comment]
@vogella I tested you branch, and it is possible to include Nebula Widgets in a Composite.
So (@wim quote) : To the batmobile, let's go !

**Comment by vogella** [comment]
Will delete after a successful build

**Pull request merged**
