### PR TITLE
Fixed warning on deprecated Number-Object constructor use since JDK9

### PR DESCRIPTION
**Pull request by jposterloh**
Second try...

### CODE REVIEW

**Review by wimjongman — APPROVED** [review]

**Comment by wimjongman** [comment]
Thanks, Jan!

**Comment by wimjongman** [comment]
You can download it from the upcoming section[1] after the build[2] is ready:

https://www.eclipse.org/windowbuilder/download.php
https://ci.eclipse.org/windowbuilder/job/org.eclipse.windowbuilder/

**Comment by lcaron** [comment]
Good job, thank you for your contribution !

**Comment by vogella** [comment]
I think this change broken the org.eclipse.wb.tests.designer.core.model.property.StandardConvertersTest

@jposterloh can you have a look and also update the tests?

**Comment by vogella** [comment]
@jposterloh please ignore, I will update the tests. I'm currently working on enabling the core tests in the Tycho build to catch such issues earlier and as I'm already looking at them, it is most likely easier for me to update them.

Would be nice if more people help with enabling more tests, see https://github.com/eclipse/windowbuilder/issues/42, we currenty have 147 with the core test suite we will have +~3600 :-o but there are even more test suites not yet executed in the Tycho build.

**Pull request merged**
