### PR TITLE
Removes custom rebase action from workflow

### PR DESCRIPTION
**Pull request by vogella**
This is now a standard feature in Github

### CODE REVIEW

**Comment by vogella** [comment]
cc @ptziegler @lcaron see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2905 for the missing rebase button in the PR UI. IIRC foundation need to active it.

**Comment by vogella** [comment]
@ptziegler how can this all be green now?

**Comment by vogella** [comment]
Btw, I added your to the Jenkins job in case of failures you will also get an email.

**Comment by ptziegler** [comment]
> how can this all be green now?

The tests are working fine on Windows, but not on Linux. For all intents and purposes, it's arbitrary which ones are uploaded to GH.

**Comment by vogella** [comment]
> > how can this all be green now?
> 
> The tests are working fine on Windows, but not on Linux. For all intents and purposes, it's arbitrary which ones are uploaded to GH.

Obviously this is very confusing for me. :-)

**Pull request merged**
